import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a href="https://nextjs.org">
            <br />
            Mouse Haunt Features!
          </a>
        </h1>

        <p className={styles.description}>
          Here you can write your suggestion for new features, as well as vote
          <br />
          on which new feature you would like to see implemented first!
        </p>

        <div className={styles.grid}>
          <a href="/suggest-feature" className={styles.card}>
            <h2>Suggest a new feature!</h2>
            <p>
              Suggest us a new feature that you think is a good idea for MH.
            </p>
          </a>

          <a href="/feature-voting" className={styles.card}>
            <h2>Feature Voting</h2>
            <p>See the list of features and vote in the best ones!</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://mousehaunt.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}>Mouse Haunt</span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
