import Link from 'next/link'
import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from '../../styles/Feature.module.css';
import axios from "axios";

type Feature = {
  id: number;
  description: string;
  votes: number;
};

const FeatureVoting: NextPage = () => {
  const [features, setFeatures] = useState<Feature[]>([]);

  useEffect(() => {
    axios
      .get("/api/features")
      .then((response) => setFeatures(response.data))
      .catch((err) => console.log(err));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>MH | Feature Voting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Features Voting</h1>

        <p className={styles.description}>
          Vote in the best features and wait for them to be implemented!
        </p>

        <div className={styles.grid}>
          {features.map((feature) => (
            // @ts-ignore
            <Link key={feature.id} href="/suggest-feature" className={styles.card}>
              <p>{feature.description}</p>
            </Link>
          ))}
        </div>
        {/* @ts-ignore */}
        <Link href="/suggest-feature" className={styles.card}>
          <h2>Suggest a new feature!</h2>
          <p>Suggest us a new feature that you think is a good idea for MH.</p>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://mousehaunt.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}>Mouse Haunt</span>
        </a>
      </footer>
    </div>
  );
};

export default FeatureVoting;
